"""ComfyUI-MIDI3D nodes package."""

from .load_model import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS
from .load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY

from .preprocess import NODE_CLASS_MAPPINGS as PREPROCESS_MAPPINGS
from .preprocess import NODE_DISPLAY_NAME_MAPPINGS as PREPROCESS_DISPLAY

from .process import NODE_CLASS_MAPPINGS as PROCESS_MAPPINGS
from .process import NODE_DISPLAY_NAME_MAPPINGS as PROCESS_DISPLAY

from .mask_utils import NODE_CLASS_MAPPINGS as MASK_MAPPINGS
from .mask_utils import NODE_DISPLAY_NAME_MAPPINGS as MASK_DISPLAY

from .texture import NODE_CLASS_MAPPINGS as TEXTURE_MAPPINGS
from .texture import NODE_DISPLAY_NAME_MAPPINGS as TEXTURE_DISPLAY

from .utils import NODE_CLASS_MAPPINGS as UTILS_MAPPINGS
from .utils import NODE_DISPLAY_NAME_MAPPINGS as UTILS_DISPLAY


# Aggregate all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PREPROCESS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROCESS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MASK_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXTURE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(UTILS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PREPROCESS_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PROCESS_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXTURE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILS_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
